---
# tasks file for common

- name: download war file from GIT reporsitory
  get_url:
    url: '{{ war_file_down_loc }}'
    dest: '/tmp/sample.war'
    mode: 0777

- name: stop the tomcat service
  service: name=tomcat state=stopped

- name: verify tomcat is stopped or not
  shell: ps -ef | grep tomcat8 | grep -v grep | wc -l
  register: tomcat_process_status

- name: create directory for backup
  file:
    path: '/backup/AIS'
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

# - name: Get a timestamp
 #  command: date +%Y%m%d%H%M%S
  # register: timestamp
- name: checking the status of the war file before backing up
  stat:
    path: "{{ war_file_loc }}/{{ war_file }}"
  regiser: backup_war_file_stat

- name: copy war file to backup folder
  copy:
    src: "{{ war_file_loc }}/{{ war_file }}"
    dest: '/backup/AIS/{{ war_file }}_backup_`date +%F`'
    remote_src: yes
  when: backup_war_file_stat.exists == True

- name: remove the deployed war files
  file:
    path: '{{ war_file_loc }}/{{ war_file_deploy}}'
    state: absent

- name: copy war file to the deployment folder
  copy:
    src: '/tmp/{{ war_file }}'
    dest: '{{ war_file_loc }}/{{ war_file }}'
    remote_src: yes
    owner: tomcat
    group: tomcat
    backup: yes
  notify: restart tomcat
  when: "tomcat_process_status.stdout|int == 0"

- name: remove java symlink from app folder
  file:
    path: "/local/apps/AIS/java"
    state: absent

- name: create java symlink again
  file:
    src: '/usr/jdk/instances/jdk1.8.0_74'
    dest: '/local/apps/AIS/java'
    owner: tomcat
    group: tomcat
    state: link

- name: remove cache Catalina folder
  file:
    path: '/opt/tomcat8/work/Catalina/localhost/{{ war_file_deploy }}'
    state: absent

- name: start tomcat service
  service: name=tomcat state=started

- name: checking the tomcat_process_status
  shell: ps -ef | grep tomcat8 | grep -v grep | wc -l
  register: tomcat_process_status_final

- debug:
    msg: "The deployment completed successfully and tomcat started"
  when: "tomcat_process_status_final.stdout| int != 0"

- debug:
    msg: "The deployment seems to be failure and tomcat not started"
  when: tomcat_process_status_final.stdout| int == 0"

