---
# tasks file for common

- name: download war file from GIT reporsitory
  get_url:
    url: '{{ war_file_down_loc }}'
    dest: '/tmp/sample.war'
    mode: 0777

- name: stop the tomcat service
  service: name=tomcat state=stopped

- name: verify tomcat is stopped or not
  shell: ps -ef | grep tomcat8 | grep -v grep | wc -l
  register: tomcat_process_status

- name: copy war file to the deployment folder
  copy:
    src: '/tmp/{{ war_file }}'
    dest: '{{ war_file_loc }}/{{ war_file }}'
    remote_src: yes
    owner: tomcat
    group: tomcat
    backup: yes
  when: "tomcat_process_status.stdout|int == 0"

- name: remove java symlink from app folder
  file:
    path: "/local/apps/AIS/java"
    state: absent

- name: create java symlink again
  file:
    src: '/usr/jdk/instances/jdk1.8.0_74'
    dest: '/local/apps/AIS/java'
    owner: tomcat
    group: tomcat
    state: link